name: 'Azure Versioned Storage Upload'
description: 'Upload a directory to Azure Blob Storage under a specified version number.'
author: 'Runly LLC'

inputs:
  connectionString:
    description: 'The storage account connection string'
    required: true
  version:
    description: 'The version of the assets to upload.'
    required: true
  container:
    description: 'The blob container to upload assets into.'
    required: true
  sourceDir:
    description: 'The source directory of assets to upload.'
    required: true

runs:
  using: 'node12'
  main: 'dist/action.js'

branding:
  icon: 'arrow-up-circle'
  color: 'blue'
  