name: 'Azure Versioned Storage Upload'
description: 'Upload a directory to Azure Blob Storage under a specified version number.'
inputs:
  storageSasUrl:
    description: 'The Blob service Shared Access Signature (SAS) URL'
    required: true
  version:
    description: 'The version of the assets to upload.'
    required: true
  container:
    description: 'The blob container to upload assets into.'
    required: true
  sourceDir:
    description: 'The source directory of assets to upload.'
    required: true
runs:
  using: 'node12'
  main: 'dist/action.js'
